FROM python:3.11.14
WORKDIR /app

# 필수 패키지 설치
RUN apt-get update && apt-get install -y ffmpeg curl

# Rust 설치
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup default 1.68.2

# requirements 복사 및 설치
COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN python -m pip install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cu121 -r requirements.txt

# 앱 소스 복사
COPY . .

CMD ["python", "main.py"]

